export enum PRODUCT_TYPE_ENG {
    FOOD = "food",
    HYGIENE = "hygiene",
    SANITARY = "sanitary",
    CLOTHING = "clothing",
    FOOTWEAR = "footwear",
    SCHOOL_SUPPLIES = "school supplies",
    OTHERS = "others"
}

export enum PRODUCT_TYPE_RO {
    FOOD = "alimente",
    HYGIENE = "materiale de igienă",
    SANITARY = "materiale sanitare",
    CLOTHING = "îmbrăcăminte",
    FOOTWEAR = "încălțăminte",
    SCHOOL_SUPPLIES = "rechizite",
    OTHERS = "altele"
}

export const productTypesRoToEngMap = new Map<string, string>([
    [PRODUCT_TYPE_RO.FOOD, PRODUCT_TYPE_ENG.FOOD],
    [PRODUCT_TYPE_RO.HYGIENE, PRODUCT_TYPE_ENG.HYGIENE],
    [PRODUCT_TYPE_RO.SANITARY, PRODUCT_TYPE_ENG.SANITARY],
    [PRODUCT_TYPE_RO.CLOTHING, PRODUCT_TYPE_ENG.CLOTHING],
    [PRODUCT_TYPE_RO.FOOTWEAR, PRODUCT_TYPE_ENG.FOOTWEAR],
    [PRODUCT_TYPE_RO.SCHOOL_SUPPLIES, PRODUCT_TYPE_ENG.SCHOOL_SUPPLIES],
    [PRODUCT_TYPE_RO.OTHERS, PRODUCT_TYPE_ENG.OTHERS],
]);

export const productTypesEngToRoMap = new Map<string, string>([
    [PRODUCT_TYPE_ENG.FOOD, PRODUCT_TYPE_RO.FOOD],
    [PRODUCT_TYPE_ENG.HYGIENE, PRODUCT_TYPE_RO.HYGIENE],
    [PRODUCT_TYPE_ENG.SANITARY, PRODUCT_TYPE_RO.SANITARY],
    [PRODUCT_TYPE_ENG.CLOTHING, PRODUCT_TYPE_RO.CLOTHING],
    [PRODUCT_TYPE_ENG.FOOTWEAR, PRODUCT_TYPE_RO.FOOTWEAR],
    [PRODUCT_TYPE_ENG.SCHOOL_SUPPLIES, PRODUCT_TYPE_RO.SCHOOL_SUPPLIES],
    [PRODUCT_TYPE_ENG.OTHERS, PRODUCT_TYPE_RO.OTHERS],
]);

export const productTypesOptions = [
    PRODUCT_TYPE_RO.FOOD, 
    PRODUCT_TYPE_RO.HYGIENE, 
    PRODUCT_TYPE_RO.SANITARY,
    PRODUCT_TYPE_RO.CLOTHING,
    PRODUCT_TYPE_RO.FOOTWEAR,
    PRODUCT_TYPE_RO.SCHOOL_SUPPLIES,
    PRODUCT_TYPE_RO.OTHERS
];